services:
  db:
    container_name: auth-server-psql # Name of the container
    image: postgres:17 # Using PostgreSQL version 17
    environment:
      POSTGRES_USER: ${DB_USER:-root} # Default user is 'root'
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root} # Default password is 'root'
      POSTGRES_DB: ${DB_NAME:-app_db} # Default database name is 'app_db'
    ports:
      - "${DB_PORT:-5444}:5432" # Porting port 5432 by default
    volumes:
      - ./db_data:/var/lib/postgresql/data # Persisting data
